spring:
  application:
    name: Healthcare Appointment

  datasource:
    username: myuser
    password: secret
    url: jdbc:postgresql://localhost:5432/healthcare_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enable: true
    locations: classpath:db/migration
    baseline-on-migrate: true

